### ISSUE TITLE
Camel code option for visual studio code

### ISSUE THREAD

**Issue by m-d-young** [heterophyllus/vscode-zemax#1]
Thank you for putting this extension together for visual studio code.  One suggestion I have is to change the function symbols like, "INSERTMFO" to "InsertMfo".  When typing "MFO" into visual studio code, it will find anything beginning with M and so on, however it won't find symbols with "MFO" buried in the name.  Because ZPL is case insensitive, the symbols could be changed to camel case and it would make searching for merit function, multi config, symbols easier.

**Comment by heterophyllus** [comment]
Thank you for the helpful suggestion.

Your suggestion seems reasonable.  In my opinion, however, we had better keep them all-uppercase for consistency with the reference manual and official ZPL samples.

I wish we could get the keyword by typing a buried clue, too.
I recommend that you try posting this improvement suggestion to vscode developers.

**Comment by m-d-young** [comment]
Thank you for your response. I believe that the suggested behavior, finding inner string fragments/buried clues, is a feature request here ([#53715](https://github.com/microsoft/vscode/issues/53715)).

**Comment by heterophyllus** [comment]
Thank you for showing the related issue and I figured out the matter had been discussed.
For now, I go on watching its proceeding and future updates.
